services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backnet
    restart: unless-stopped

networks:
  backnet:
    driver: bridge

volumes:
  postgres:
