spring:
  application:
    name: ahub
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social
    username: admin
    password: admin
  security:
    oauth2:
      authorizationserver:
        endpoint:
          authorization-uri: login
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
management:
  endpoints:
    web:
      exposure:
        include: "*"

minio:
  accessKey: admin
  secretKey: StrongAdmin
  url: http://localhost:9000

server:
  port: 8080


springdoc:
  api-docs:
    path: /api-doc